heat_template_version: 2014-10-16

description: Core library for creating and attaching a volume to an instance

parameters:
  volume_size:
    type: number
    description: Size of the volume to attach to the instance
    default: 10
    constraints:
      - range: { min: 1, max: 10000 }
        description: Size in GB of attached volumes must be between [1-10000]
  volume_name:
    type: string
    description: The name of the volume to attach to the instance
  instance_id:
    type: string
    description: The id of the server to attach the volume to
    
resources:
  volume:
    type: OS::Cinder::Volume
    properties:
      name: { get_param: volume_name }
      size: { get_param: volume_size }
  volume_attachment:
    type: OS::Cinder::VolumeAttachment
    properties:
      volume_id: { get_resource: volume }
      instance_uuid: { get_param: instance_id}
